// This file contains the minimal data needed for the initial page load.
const initialTools = [
  { "id": "App-Usage-Monitor", "Name": "App Usage Monitor", "Category": "Utility" },
  { "id": "Asthma-Trigger-Monitor", "Name": "Asthma Trigger Monitor", "Category": "Health" },
  { "id": "Auto-Renewal-Alert", "Name": "Auto Renewal Alert", "Category": "Financial" },
  { "id": "Baby-Growth-Tracker", "Name": "Baby Growth Tracker", "Category": "Health" },
  { "id": "Bac-Blood-Alcohol-Estimator", "Name": "Bac (Blood Alcohol) Estimator", "Category": "Health" },
  { "id": "Backpack-Weight-Calculator", "Name": "Backpack Weight Calculator", "Category": "Lifestyle" },
  { "id": "Baking-Temperature-Converter", "Name": "Baking Temperature Converter", "Category": "Utility" },
  { "id": "Battery-Health-Monitor", "Name": "Battery Health Monitor", "Category": "Utility" },
  { "id": "Battery-Replacement-Tracker", "Name": "Battery Replacement Tracker", "Category": "Utility" },
  { "id": "Beard-Trimming-Timer", "Name": "Beard Trimming Timer", "Category": "Lifestyle" },
  { "id": "Belt-Size-Finder", "Name": "Belt Size Finder", "Category": "Lifestyle" },
  { "id": "Bike-Route-Planner", "Name": "Bike Route Planner", "Category": "Fitness" },
  { "id": "Bike-Share-Availability-Checker", "Name": "Bike Share Availability Checker", "Category": "Utility" },
  { "id": "Birthday-Reminder", "Name": "Birthday Reminder", "Category": "Lifestyle" },
  { "id": "Blood-Pressure-Monitor", "Name": "Blood Pressure Monitor", "Category": "Health" },
  { "id": "Blue-Light-Exposure-Monitor", "Name": "Blue Light Exposure Monitor", "Category": "Health" },
  { "id": "Body-Measurement-Tracker", "Name": "Body Measurement Tracker", "Category": "Health" },
  { "id": "Boiling-Water-Timer", "Name": "Boiling Water Timer", "Category": "Utility" },
  { "id": "Book-Page-Counter", "Name": "Book Page Counter", "Category": "Education" },
  { "id": "Break-Even-Calculator", "Name": "Break Even Calculator", "Category": "Financial" },
  { "id": "Breathing-Exercise-Timer", "Name": "Breathing Exercise Timer", "Category": "Health" },
  { "id": "Bucket-List-Organizer", "Name": "Bucket List Organizer", "Category": "Lifestyle" },
  { "id": "Budget-Planner", "Name": "Budget Planner", "Category": "Financial" },
  { "id": "Caffeine-Intake-Tracker", "Name": "Caffeine Intake Tracker", "Category": "Health" },
  { "id": "Call-Duration-Tracker", "Name": "Call Duration Tracker", "Category": "Utility" },
  { "id": "Calorie-Counter", "Name": "Calorie Counter", "Category": "Health" },
  { "id": "Calorie-Intake-Calculator", "Name": "Calorie Intake Calculator", "Category": "Health" },
  { "id": "Camping-Gear-Checklist", "Name": "Camping Gear Checklist", "Category": "Lifestyle" },
  { "id": "Carb-Counter", "Name": "Carb Counter", "Category": "Health" },
  { "id": "Carb-Cycling-Planner", "Name": "Carb Cycling Planner", "Category": "Fitness" },
  { "id": "Carbon-Footprint-Calculator", "Name": "Carbon Footprint Calculator", "Category": "Environment" },
  { "id": "Carbon-Offset-Estimator", "Name": "Carbon Offset Estimator", "Category": "Environment" },
  { "id": "Car-Insurance-Cost-Checker", "Name": "Car Insurance Cost Checker", "Category": "Financial" },
  { "id": "Car-Loan-Calculator", "Name": "Car Loan Calculator", "Category": "Financial" },
  { "id": "Car-Maintenance-Reminder", "Name": "Car Maintenance Reminder", "Category": "Utility" },
  { "id": "Car-Rental-Cost-Calculator", "Name": "Car Rental Cost Calculator", "Category": "Financial" },
  { "id": "Car-Wash-Reminder", "Name": "Car Wash Reminder", "Category": "Utility" },
  { "id": "Cashback-Estimator", "Name": "Cashback Estimator", "Category": "Financial" },
  { "id": "Catering-Portion-Calculator", "Name": "Catering Portion Calculator", "Category": "Lifestyle" },
  { "id": "Cholesterol-Level-Checker", "Name": "Cholesterol Level Checker", "Category": "Health" },
  { "id": "Clothing-Size-Converter", "Name": "Clothing Size Converter", "Category": "Lifestyle" },
  { "id": "Cloud-Storage-Usage-Monitor", "Name": "Cloud Storage Usage Monitor", "Category": "Utility" },
  { "id": "Coffee-Brewing-Timer", "Name": "Coffee Brewing Timer", "Category": "Lifestyle" },
  { "id": "Ac-Filter-Replacement-Reminder", "Name": "Ac Filter Replacement Reminder", "Category": "Utility" },
  { "id": "Air-Quality-Checker", "Name": "Air Quality Checker", "Category": "Environment" },
  { "id": "Alcohol-Unit-Calculator", "Name": "Alcohol Unit Calculator", "Category": "Health" },
  { "id": "Allergy-Forecast-Checker", "Name": "Allergy Forecast Checker", "Category": "Health" },
  { "id": "Allergy-Free-Recipe-Converter", "Name": "Allergy Free Recipe Converter", "Category": "Health" },
  { "id": "Anniversary-Tracker", "Name": "Anniversary Tracker", "Category": "Lifestyle" },
  { "id": "Appliance-Energy-Cost-Calculator", "Name": "Appliance Energy Cost Calculator", "Category": "Utility" },
  { "id": "Dry-Cleaning-Tracker", "Name": "Dry Cleaning Tracker", "Category": "Daily" },
  { "id": "Egg-Boiling-Timer", "Name": "Egg Boiling Timer", "Category": "Daily" },
  { "id": "Daily-Water-Intake-Tracker", "Name": "Daily Water Intake Tracker", "Category": "Daily" }
];